platzigram/urls.py
# from django.contrib import admin

#Django
from django.contrib import admin
from django.conf import settings # Para mostrar imagenes de usuario al darle clic
from django.conf.urls.static import static # Para mostrar imagenes de usuario al darle clic
from django.urls import path, include


urlpatterns = [
    path('admin/',admin.site.urls),
    
    path('',include(('posts.urls','posts'),namespace='posts')),
    path('users/',include(('users.urls','users'),namespace='users')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

posts/urls.py
#Django
from django.urls import path

from posts import views

urlpatterns = [


    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='feed'),
    path(
        route='posts/new/',
        view=views.create_post,
        name='create'),

]

users/urls.py
# Django
from django.urls import path

# View
from users import views


urlpatterns = [
    # Posts
    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    path(
        route='signup/',
        view=views.signup,
        name='signup'),
    path(
        route='login/',
        view=views.login_view,
        name='login'),
    path(
        route='logout/',
        view=views.logout_view,
        name='logout'),
    path(
        route='me/profile/',
        view=views.update_profile,
        name='update'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="icon" href="{% static 'img/favico.png' %}">


</head>
<body>

    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>

</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:feed' %}">
            <img src="{% static "img/instagram.png" %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    {% if request.user.profile.picture %}
                        <a href="{% url 'users:detail' request.user.username %}"><img src="{{ request.user.profile.picture.url }}" class="rounded-circle" height="45" /></a>
                    {% else%}
                        <a href="{% url 'users:update' %}"><img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" /></a>
                    {% endif %}
                    <!-- <a href="">
                        <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                    </a> -->
                </li>
                <!-- Add new post -->
                <li class="nav-item nav-icon">
                    <a href="{% url 'posts:create' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav> 